sudo: required
language: python
python:
  - "2.7"
env:
  - PYTHONPATH=./tests/mocks
before_install:
  - sudo apt-get install libxml2-dev libxslt-dev python-dev python-pyicu
install:
  - xargs -a requirements.txt -n 1 pip install
script:
  - python tests/runtests.py

